export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

/** Vacío tipado para tablas sin FKs en el cliente */
type NoRelationships = {
  foreignKeyName: string;
  columns: string[];
  isOneToOne?: boolean;
  referencedRelation: string;
  referencedColumns: string[];
}[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "12";
  };
  public: {
    Tables: {
      empresas: {
        Row: {
          id: string;
          owner_id: string;
          nombre_empresa: string;
          slug: string;
          color_marca: string;
          logo_url: string | null;
          privacy_url: string | null;
          precio_eur_kwp: number;
          tarifa_kwh_override: number | null;
          ratio_autoconsumo: number;
          kwp_max: number;
          gtm_id: string | null;
          webhook_url: string | null;
          plan: "basic" | "pro" | null;
          moneda_facturacion: "EUR" | "USD";
          paypal_subscription_id: string | null;
          paypal_payer_id: string | null;
          estado_suscripcion: "pending" | "active" | "suspended" | "cancelled";
          leads_limite_mes: number;
          leads_usados_mes: number;
          periodo_reset: string | null;
          proximo_cobro: string | null;
          trial_ends_at: string | null;
          terms_accepted_at: string | null;
          early_bird: boolean;
          early_bird_discount_pct: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          nombre_empresa: string;
          slug: string;
          color_marca?: string;
          logo_url?: string | null;
          privacy_url?: string | null;
          precio_eur_kwp?: number;
          tarifa_kwh_override?: number | null;
          ratio_autoconsumo?: number;
          kwp_max?: number;
          gtm_id?: string | null;
          webhook_url?: string | null;
          plan?: "basic" | "pro" | null;
          moneda_facturacion?: "EUR" | "USD";
          paypal_subscription_id?: string | null;
          paypal_payer_id?: string | null;
          estado_suscripcion?: "pending" | "active" | "suspended" | "cancelled";
          leads_limite_mes?: number;
          leads_usados_mes?: number;
          periodo_reset?: string | null;
          proximo_cobro?: string | null;
          trial_ends_at?: string | null;
          terms_accepted_at?: string | null;
          early_bird?: boolean;
          early_bird_discount_pct?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          nombre_empresa?: string;
          slug?: string;
          color_marca?: string;
          logo_url?: string | null;
          privacy_url?: string | null;
          precio_eur_kwp?: number;
          tarifa_kwh_override?: number | null;
          ratio_autoconsumo?: number;
          kwp_max?: number;
          gtm_id?: string | null;
          webhook_url?: string | null;
          plan?: "basic" | "pro" | null;
          moneda_facturacion?: "EUR" | "USD";
          paypal_subscription_id?: string | null;
          paypal_payer_id?: string | null;
          estado_suscripcion?: "pending" | "active" | "suspended" | "cancelled";
          leads_limite_mes?: number;
          leads_usados_mes?: number;
          periodo_reset?: string | null;
          proximo_cobro?: string | null;
          trial_ends_at?: string | null;
          terms_accepted_at?: string | null;
          early_bird?: boolean;
          early_bird_discount_pct?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: NoRelationships;
      };
      equipo: {
        Row: {
          id: string;
          empresa_id: string;
          usuario_id: string;
          rol: "admin" | "comercial";
          created_at: string;
        };
        Insert: {
          id?: string;
          empresa_id: string;
          usuario_id: string;
          rol?: "admin" | "comercial";
          created_at?: string;
        };
        Update: {
          id?: string;
          empresa_id?: string;
          usuario_id?: string;
          rol?: "admin" | "comercial";
          created_at?: string;
        };
        Relationships: NoRelationships;
      };
      leads: {
        Row: {
          id: string;
          empresa_id: string;
          localidad_id: string | null;
          fecha: string;
          nombre: string;
          telefono: string;
          email: string;
          tipo_inmueble: "residencial" | "comercial";
          comunidad: string | null;
          ciudad: string | null;
          gasto_luz: number | null;
          consumo_kwh: number | null;
          gasto_mensual_eur: number | null;
          consumo_kwh_mensual: number | null;
          campo_origen_consumo: "gasto" | "kwh" | null;
          precio_efectivo_kwh: number | null;
          desglose_factura: Json | null;
          kwp_estimado: number | null;
          ahorro_anual_eur: number | null;
          payback_anos: number | null;
          produccion_anual_kwh: number | null;
          estado: "Nuevo" | "Contactado" | "Visita" | "Presupuesto" | "Cerrado" | "Descartado";
          assigned_to: string | null;
          notas: string | null;
          utm_source: string | null;
          utm_medium: string | null;
          utm_campaign: string | null;
          consentimiento_rgpd: boolean;
          es_prueba: boolean;
          ip_hash: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          empresa_id: string;
          localidad_id?: string | null;
          fecha?: string;
          nombre: string;
          telefono: string;
          email: string;
          tipo_inmueble: "residencial" | "comercial";
          comunidad?: string | null;
          ciudad?: string | null;
          gasto_luz?: number | null;
          consumo_kwh?: number | null;
          gasto_mensual_eur?: number | null;
          consumo_kwh_mensual?: number | null;
          campo_origen_consumo?: "gasto" | "kwh" | null;
          precio_efectivo_kwh?: number | null;
          desglose_factura?: Json | null;
          kwp_estimado?: number | null;
          ahorro_anual_eur?: number | null;
          payback_anos?: number | null;
          produccion_anual_kwh?: number | null;
          estado?: "Nuevo" | "Contactado" | "Visita" | "Presupuesto" | "Cerrado" | "Descartado";
          assigned_to?: string | null;
          notas?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          consentimiento_rgpd: boolean;
          es_prueba?: boolean;
          ip_hash?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          empresa_id?: string;
          localidad_id?: string | null;
          fecha?: string;
          nombre?: string;
          telefono?: string;
          email?: string;
          tipo_inmueble?: "residencial" | "comercial";
          comunidad?: string | null;
          ciudad?: string | null;
          gasto_luz?: number | null;
          consumo_kwh?: number | null;
          gasto_mensual_eur?: number | null;
          consumo_kwh_mensual?: number | null;
          campo_origen_consumo?: "gasto" | "kwh" | null;
          precio_efectivo_kwh?: number | null;
          desglose_factura?: Json | null;
          kwp_estimado?: number | null;
          ahorro_anual_eur?: number | null;
          payback_anos?: number | null;
          produccion_anual_kwh?: number | null;
          estado?: "Nuevo" | "Contactado" | "Visita" | "Presupuesto" | "Cerrado" | "Descartado";
          assigned_to?: string | null;
          notas?: string | null;
          utm_source?: string | null;
          utm_medium?: string | null;
          utm_campaign?: string | null;
          consentimiento_rgpd?: boolean;
          es_prueba?: boolean;
          ip_hash?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: NoRelationships;
      };
      localidades: {
        Row: {
          id: string;
          nombre: string;
          slug: string;
          provincia: string;
          ccaa: string;
          codigo_ine: string | null;
          lat: number;
          lon: number;
          produccion_kwh_kwp_anual: number;
          precio_energia_kwh: number;
          peaje_te_kwh: number;
          cargo_sistema_kwh: number;
          precio_potencia_kw_mes: number;
          alquiler_contador_mes: number;
          potencia_tipica_residencial_kw: number;
          potencia_tipica_comercial_kw: number;
          usa_igic: boolean;
          iva_pct: number;
          igic_energia_pct: number;
          activo: boolean;
          updated_at: string;
        };
        Insert: {
          id?: string;
          nombre: string;
          slug: string;
          provincia: string;
          ccaa: string;
          codigo_ine?: string | null;
          lat: number;
          lon: number;
          produccion_kwh_kwp_anual: number;
          precio_energia_kwh?: number;
          peaje_te_kwh?: number;
          cargo_sistema_kwh?: number;
          precio_potencia_kw_mes?: number;
          alquiler_contador_mes?: number;
          potencia_tipica_residencial_kw?: number;
          potencia_tipica_comercial_kw?: number;
          usa_igic?: boolean;
          iva_pct?: number;
          igic_energia_pct?: number;
          activo?: boolean;
          updated_at?: string;
        };
        Update: {
          id?: string;
          nombre?: string;
          slug?: string;
          provincia?: string;
          ccaa?: string;
          codigo_ine?: string | null;
          lat?: number;
          lon?: number;
          produccion_kwh_kwp_anual?: number;
          precio_energia_kwh?: number;
          peaje_te_kwh?: number;
          cargo_sistema_kwh?: number;
          precio_potencia_kw_mes?: number;
          alquiler_contador_mes?: number;
          potencia_tipica_residencial_kw?: number;
          potencia_tipica_comercial_kw?: number;
          usa_igic?: boolean;
          iva_pct?: number;
          igic_energia_pct?: number;
          activo?: boolean;
          updated_at?: string;
        };
        Relationships: NoRelationships;
      };
      invitaciones_equipo: {
        Row: {
          id: string;
          empresa_id: string;
          email: string;
          rol: "admin" | "comercial";
          token: string;
          expira_at: string;
          aceptada_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          empresa_id: string;
          email: string;
          rol?: "admin" | "comercial";
          token: string;
          expira_at: string;
          aceptada_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          empresa_id?: string;
          email?: string;
          rol?: "admin" | "comercial";
          token?: string;
          expira_at?: string;
          aceptada_at?: string | null;
          created_at?: string;
        };
        Relationships: NoRelationships;
      };
      lead_actividad: {
        Row: {
          id: string;
          lead_id: string;
          usuario_id: string | null;
          estado_anterior: string | null;
          estado_nuevo: string | null;
          nota: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          lead_id: string;
          usuario_id?: string | null;
          estado_anterior?: string | null;
          estado_nuevo?: string | null;
          nota?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          lead_id?: string;
          usuario_id?: string | null;
          estado_anterior?: string | null;
          estado_nuevo?: string | null;
          nota?: string | null;
          created_at?: string;
        };
        Relationships: NoRelationships;
      };
      parametros_tarifa_anual: {
        Row: {
          id: string;
          anio: number;
          precio_energia_medio: number;
          peaje_te_medio: number;
          cargo_sistema_medio: number;
          precio_potencia_kw_mes: number;
          iee_pct: number;
          iva_pct: number;
          activo: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          anio: number;
          precio_energia_medio?: number;
          peaje_te_medio?: number;
          cargo_sistema_medio?: number;
          precio_potencia_kw_mes?: number;
          iee_pct?: number;
          iva_pct?: number;
          activo?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          anio?: number;
          precio_energia_medio?: number;
          peaje_te_medio?: number;
          cargo_sistema_medio?: number;
          precio_potencia_kw_mes?: number;
          iee_pct?: number;
          iva_pct?: number;
          activo?: boolean;
          created_at?: string;
        };
        Relationships: NoRelationships;
      };
      contact_inquiries: {
        Row: {
          id: string;
          nombre: string;
          email: string;
          empresa: string | null;
          telefono: string | null;
          mensaje: string;
          consentimiento_rgpd: boolean;
          ip_hash: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          nombre: string;
          email: string;
          empresa?: string | null;
          telefono?: string | null;
          mensaje: string;
          consentimiento_rgpd?: boolean;
          ip_hash?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          nombre?: string;
          email?: string;
          empresa?: string | null;
          telefono?: string | null;
          mensaje?: string;
          consentimiento_rgpd?: boolean;
          ip_hash?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Relationships: NoRelationships;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
  };
};

export type Empresa = Database["public"]["Tables"]["empresas"]["Row"];
export type Lead = Database["public"]["Tables"]["leads"]["Row"];
export type LocalidadRow = Database["public"]["Tables"]["localidades"]["Row"];
